WITH  activities AS (
	SELECT

		SUGGESTION_ID,
		CAMPAIGN_FK AS CAMPAIGN_ID,
		STORE_FK AS STORE_ID,
		SELLER_FK AS SELLER_ID,
		CUSTOMER_FK AS CUSTOMER_ID,
		if(F.SUGGESTION_FK is NULL, DATE, F.CREATE_DATE) AS CONTACT_DATE,
		if(F.SUGGESTION_FK IS NOT NULL AND F.ENABLED = 1, 1, 0) AS CONTACT_STARTED,
		F.STATUS AS CONTACT_SUCESS

	FROM {{source('prod', 'APP_SUGGESTIONS')}} S
	LEFT JOIN {{source('prod', 'APP_FOLLOWUP')}} F ON SUGGESTION_ID = SUGGESTION_FK
	WHERE CONTACT_DATE = today() -1
)

SELECT * FROM activities
